name: Inverse-Kinematics-Prediction
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python
  - pandas
  - numpy
  - requests
  - matplotlib
  - pytorch
  - scikit-learn
  - ipykernel
  - plotly
  - seaborn
  - nbformat>=4.2.0